# Generated by Django 5.0.3 on 2024-03-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('blood', 'Blood Test'), ('diabetes', 'Diabetes Test')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submission', 'Submission'), ('evaluation', 'Evaluation'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('blood_sugar_level_result', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('insulin_level_result', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_test_reports', to=settings.AUTH_USER_MODEL)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_test_report', to='docAI.test')),
            ],
        ),
        migrations.CreateModel(
            name='BloodTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submission', 'Submission'), ('evaluation', 'Evaluation'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('RBC_result', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('PCV_result', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('WBC_result', models.IntegerField(default=0)),
                ('Neutrophils_result', models.IntegerField(default=0)),
                ('Lymphocytes_result', models.IntegerField(default=0)),
                ('Eosinophils_result', models.IntegerField(default=0)),
                ('Monocytes_result', models.IntegerField(default=0)),
                ('Basophils_result', models.IntegerField(default=0)),
                ('Platelet_count', models.IntegerField(default=0)),
                ('hemoglobin_result', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('blood_pressure_result', models.CharField(default='', max_length=20)),
                ('cholesterol_level_result', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_test_reports', to=settings.AUTH_USER_MODEL)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_test_report', to='docAI.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docAI.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'test')},
            },
        ),
    ]
