# Generated by Django 5.0.3 on 2024-03-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docAI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='test',
        ),
    ]
