# Generated by Django 5.0.3 on 2024-03-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docAI', '0003_bloodtestreport_include_basophils_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtestreport',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diabetestestreport',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
