# Generated by Django 5.0.3 on 2024-03-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docAI', '0003_alter_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
