# Generated by Django 5.0.3 on 2024-03-15 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docAI', '0005_remove_test_applied_by_test_customers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='customers',
        ),
        migrations.AddField(
            model_name='test',
            name='applied_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer_tests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
