# Generated by Django 5.0.3 on 2024-03-16 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docAI', '0006_remove_test_customers_test_applied_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='docAI.test')),
                ('additional_info', models.TextField()),
            ],
            bases=('docAI.test',),
        ),
        migrations.CreateModel(
            name='DiabetesTest',
            fields=[
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='docAI.test')),
                ('fasting_required', models.BooleanField(default=False)),
            ],
            bases=('docAI.test',),
        ),
    ]
