# Generated by Django 5.0.3 on 2024-03-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docAI', '0007_bloodtest_diabetestest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetestest',
            name='test',
        ),
        migrations.DeleteModel(
            name='BloodTest',
        ),
        migrations.DeleteModel(
            name='DiabetesTest',
        ),
    ]
