# Generated by Django 5.0.3 on 2024-03-16 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docAI', '0008_remove_diabetestest_test_delete_bloodtest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'blood'), (2, 'diabetes')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='assigned_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_tests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submission', 'Submission'), ('evaluation', 'Evaluation'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='types',
            field=models.ManyToManyField(to='docAI.type'),
        ),
    ]
