# Generated by Django 5.0.3 on 2024-03-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docAI', '0009_type_alter_test_applied_by_alter_test_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='types',
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('blood', 'Blood Test'), ('diabetes', 'Diabetes Test')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BloodTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_result', models.CharField(max_length=20)),
                ('cholesterol_level_result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_test_report', to='docAI.test')),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_sugar_level_result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insulin_level_result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_test_report', to='docAI.test')),
            ],
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
