# Generated by Django 5.0.3 on 2024-03-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pictures'),
        ),
    ]
